let learningProgress={};let progressAvailable=false;let progressLoading=true;let saveBusy=false;
const oldHome=showHome,oldItem=showItem,oldCard=card;
const progressOf=id=>learningProgress[id]||{position:'',completed:[],updated_at:''};
function progressNotice(){return progressLoading?'Loading saved progress…':progressAvailable?'Your saved place and completed lessons are remembered in this browser.':'Saved progress is unavailable right now. You can still read and explore.';}
showHome=function(){oldHome();const recent=Object.entries(learningProgress).filter(([id,p])=>catalog.some(r=>r.id===id)&&p.position).sort((a,b)=>b[1].updated_at.localeCompare(a[1].updated_at)).slice(0,3);const box=document.createElement('section');box.className='continue-panel';box.innerHTML='<h2>Continue learning</h2><p class="meta">'+esc(progressNotice())+'</p>'+(recent.length?recent.map(([id,p])=>{const r=catalog.find(x=>x.id===id);return '<a class="resume-link" href="#item/'+id+'"><strong>'+esc(r.title)+'</strong><span>Return to your saved place</span></a>'}).join(''):'<p>Open a book or classroom, then tap <strong>Save my place</strong> to return here later.</p>');main.querySelector('.welcome').after(box)};
card=function(r){const html=oldCard(r);const p=progressOf(r.id);const note=p.completed.length?'<p class="completion-note">✓ '+p.completed.length+' '+(p.completed.includes('resource')?'resource completed':'sections completed')+'</p>':'';return html.replace('<div class="actions">',note+'<div class="actions">')};
showItem=function(id){oldItem(id);const r=catalog.find(x=>x.id===id);if(!r||!r.content)return;
 const reader=main.querySelector('.reader');if(!reader)return;
 const headings=[...reader.querySelectorAll('h2,h3')].filter(h=>h.textContent.trim());headings.forEach((h,i)=>h.id='section-'+i);
 const p=progressOf(id);let chosen=headings.some(h=>h.id===p.position)?p.position:(headings[0]?.id||'resource');
 const tools=document.createElement('section');tools.className='lesson-navigation';
 tools.innerHTML='<h2>'+(headings.length?'Find your lesson or chapter':'Your reading progress')+'</h2>'+(headings.length?'<label for="lesson-choice">Choose a section</label><select id="lesson-choice">'+headings.map(h=>'<option value="'+h.id+'">'+esc(h.textContent)+'</option>').join('')+'</select>':'')+'<div class="actions">'+(headings.length?'<button class="button secondary" id="jump-lesson">Go to section</button>':'')+'<button class="button" id="save-place">Save my place</button><button class="button secondary" id="complete-lesson"></button></div><p id="save-status" role="status" class="meta">'+esc(progressNotice())+'</p>';
 reader.before(tools);const choice=tools.querySelector('select');if(choice)choice.value=chosen;
 const complete=tools.querySelector('#complete-lesson');const save=tools.querySelector('#save-place');const status=tools.querySelector('#save-status');
 function update(){const done=progressOf(id).completed.includes(chosen);complete.textContent=done?'✓ Completed — undo':'Mark '+(headings.length?'section':'resource')+' complete';complete.disabled=saveBusy||!progressAvailable;save.disabled=saveBusy||!progressAvailable;}
 function jump(){if(chosen==='resource'){reader.scrollIntoView({behavior:'smooth'});return}reader.querySelector('#'+chosen)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
 if(choice)choice.addEventListener('change',()=>{chosen=choice.value;update()});tools.querySelector('#jump-lesson')?.addEventListener('click',jump);
 async function persist(completing){if(saveBusy||!progressAvailable)return;saveBusy=true;update();status.textContent='Saving…';const current=progressOf(id);const completed=[...current.completed];if(completing){const i=completed.indexOf(chosen);if(i>=0)completed.splice(i,1);else completed.push(chosen)}try{const response=await wonderworldOfflineFetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resourceId:id,position:chosen,completed})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not save. Please try again.');learningProgress[id]={position:chosen,completed,updated_at:data.updatedAt};status.textContent=completing?'Your completion record is saved.':'Your place is saved. Find it under Continue learning.';}catch(e){status.textContent=e.message;}finally{saveBusy=false;update();}}
 save.addEventListener('click',()=>persist(false));complete.addEventListener('click',()=>persist(true));update();
 if(p.position&&p.position!=='resource')requestAnimationFrame(()=>requestAnimationFrame(jump));
};
wonderworldOfflineFetch('/api/progress',{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);for(const row of data.progress){try{learningProgress[row.resource_id]={position:row.position,completed:JSON.parse(row.completed),updated_at:row.updated_at}}catch{}}progressAvailable=true;}).catch(()=>{}).finally(()=>{progressLoading=false;if(catalog.length)navigate()});
