/* Subject-aware presentation only. Existing content, event handlers and saved-state keys remain owned by their original pages. */
(()=>{'use strict';
const script=document.currentScript;const base=new URL('.',script.src);const asset=k=>new URL('rooms/'+k+'.svg',base).href;
const palettes={atrium:['#e8d8b8','#8a4b76'],coding:['#c8e0e9','#245e83'],word:['#d3deed','#2d579c'],excel:['#cfdfcf','#28694d'],powerpoint:['#ecd6c7','#ac542c'],access:['#e4ced7','#933f5a'],reading:['#e8d6c0','#885235'],games:['#d2c8e9','#764ca6'],practice:['#cae0df','#247977'],helpdesk:['#dbcdbc','#88602e'],reference:['#d9d4e6','#695789'],writing:['#eadcbe','#936f30'],creative:['#f2d3ca','#b95b53'],projects:['#cee0e6','#376f81'],puzzle:['#e4d6ef','#8152a0'],visual:['#cce4e7','#2c7e86'],music:['#e7cad7','#984971'],cozy:['#edd9bb','#96734b'],business:['#d8d8cc','#617454'],events:['#ecd3dc','#97596f'],history:['#dfd6bc','#8f7743'],ancient:['#e6d2b2','#a47842'],royal:['#e0cce6','#795c91'],western:['#d9c29d','#8e6340'],maritime:['#c8dae0','#3d687e'],geography:['#d9e0c3','#56784c'],science:['#cbded8','#387970'],court:['#ddd2be','#82704d'],news:['#d7dde3','#657785'],memory:['#d5d3e9','#74628e']};
const categories={'Classrooms':'coding','Reading Room':'reading','Game Room':'games','Practice Labs':'practice','Help Desk':'helpdesk','Reference Center':'reference','Assignments & Writing':'writing','Activities & Playground':'creative','My Projects':'projects','Puzzle Library':'puzzle','Visual Match & Identify':'visual'};
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function choose(value,fallback='atrium'){const s=String(value).toLowerCase();for(const [pattern,key] of [[/game show|game night/,'games'],[/titanic|maritime|ocean|ship/,'maritime'],[/western|frontier|cowboy/,'western'],[/myth|ancient|egypt|greek|rome/,'ancient'],[/fairy|storybook|royal|castle|kingdom/,'royal'],[/geograph|map |explorer/,'geography'],[/sing|music|vocal|rhythm|performance/,'music'],[/word(?! search| ladder| &)|document/,'word'],[/excel|spreadsheet/,'excel'],[/powerpoint|presentation/,'powerpoint'],[/access|database|record/,'access'],[/help desk|helpdesk|troubleshoot|technician|cable|port |computer part|diagnos/,'helpdesk'],[/cozy|gentle|rest/,'cozy'],[/case file|court|evidence/,'court'],[/newspaper|social media/,'news'],[/business|payment|quote|invoice|career|clerical/,'business'],[/event planning|occasion/,'events'],[/what happens|science|experiment/,'science'],[/memory|hidden-object|build it from/,'memory'],[/history|historical|world war|civil rights|revolution|medieval|renaissance|victorian|civil war|space age/,'history'],[/puzzle|sudoku|wordsearch|word search|ladder|logic|escape/,'puzzle'],[/picture|visual|symbol|identify/,'visual'],[/game|school|yesterday/,'games'],[/coding|python|backend|script|css|html|form|debug|button|web |website|layout|founder|service card|portfolio|publish|hosting/,'coding'],[/reading|book|library/,'reading'],[/writing|research|teacher/,'writing'],[/brand|creative|art |design/,'creative']])if(pattern.test(s))return key;return categories[value]||fallback}
function scene(key,title,exit){const f=document.createElement('figure');f.className='themed-room';f.dataset.theme=key;const door=exit?'<a class="room-exit" href="'+safe(exit)+'" aria-label="Return to the previous room"><span>EXIT</span>Return</a>':'';f.innerHTML='<img class="room-interior" src="'+asset(key)+'" alt="" width="800" height="430"><figcaption class="room-plaque">'+safe(title)+'</figcaption>'+door;return f}
function tone(key){const p=palettes[key]||palettes.atrium;document.body.dataset.roomTheme=key;document.body.style.setProperty('--room-wall',p[0]);document.body.style.setProperty('--room-accent',p[1])}
function decorateCards(root,selector){root.querySelectorAll(selector).forEach(card=>{if(card.querySelector(':scope > .room-thumb'))return;const title=card.querySelector('h2,h3')?.textContent||card.textContent;const key=choose(title,document.body.dataset.roomTheme);const img=document.createElement('img');img.className='room-thumb';img.src=asset(key);img.alt='';img.width=800;img.height=430;img.loading='lazy';card.prepend(img);card.dataset.roomTheme=key})}
let pending=false,lastContext='';function update(){pending=false;const main=document.querySelector('#main'),office=document.querySelector('#office-stage'),room=document.querySelector('#room'),stage=document.querySelector('#stage'),history=document.querySelector('#learning');
let target=main||office||room||stage;let title=target?.querySelector('h1')?.textContent||'Wonderworld';let key='atrium',exit=new URL('index.html',base).href;
if(main){const hash=location.hash.slice(1);if(hash.startsWith('area/')){const name=decodeURIComponent(hash.slice(5));key=categories[name]||choose(name);title=name}else if(hash.startsWith('item/')){const id=hash.slice(5),entry=window.WONDERWORLD_CATALOG?.find(r=>r.id===id);key=choose(entry?.title||title,categories[entry?.category]||'reading');exit='#area/'+encodeURIComponent(entry?.category||'Reading Room')}else{title='Wonderworld Hall';key='atrium';exit=null}}
else if(office){const parts=location.hash.slice(1).split('/');let app=parts[0]==='lesson'?parts[1]:parts[0];if(parts[0]==='assignment')app=window.OFFICE_CLASSROOMS?.assignments.find(a=>String(a.number)===parts[1])?.app;key=choose(app||title,'business');if(parts[0]==='all'||!location.hash){key='business';title='Microsoft Office Campus'}exit='#all'}
else if(room){key=choose(title,'coding');const tag=room.querySelector('.quizboard .label')?.textContent;if(tag)key=choose(title+' '+tag,key);if(title.includes('Report Card')||title.includes('Take your seat')){key='coding';title='Classroom Challenge Hall'}exit='#home'}
else if(stage){key=choose(title,'puzzle');exit='#adventures';if(location.hash==='#passport')key='reference'}
if(history){target=history.classList.contains('hidden')?document.querySelector('#winggrid'):history;title=history.classList.contains('hidden')?'History House':document.querySelector('#winglabel')?.textContent||'History House';key=choose(title,'history');exit=history.classList.contains('hidden')?new URL('index.html',base).href:null}
if(!target){target=document.querySelector('main');key=choose(document.title,'history');title=document.querySelector('h1')?.textContent||document.title}
if(!target)return;tone(key);const signature=key+'|'+title;let banner=target.querySelector(':scope > .themed-room');const inQuiz=!!target.querySelector('#clock,#office-next,#timer')||!!document.querySelector('#workspace:not(.hidden)');if(!banner||banner.dataset.context!==signature){const next=scene(key,title,exit);next.dataset.context=signature;next.classList.toggle('compact-room',inQuiz);if(banner)banner.replaceWith(next);else target.prepend(next)}else banner.classList.toggle('compact-room',inQuiz);
if(main&&!location.hash.slice(1).startsWith('area/')&&!location.hash.slice(1).startsWith('item/')){const grid=main.querySelector('.worldgrid'),head=main.querySelector('.sectionhead'),scene=main.querySelector(':scope > .themed-room');if(grid&&head&&scene&&scene.nextElementSibling!==head){scene.after(head,grid)}}
decorateCards(target,'.worldcard,.office-room,.desk,.deck,#wingcards .card');if(room&&title==='Take your seat, Templar')decorateCards(room,'.desk');lastContext=signature}
function schedule(){if(!pending){pending=true;requestAnimationFrame(update)}}
window.WonderRooms={choose,scene,refresh:schedule};const targets=['#main','#room','#office-stage','#stage','#winggrid','#learning'];for(const sel of targets){const node=document.querySelector(sel);if(node)new MutationObserver(records=>{if(records.some(r=>r.addedNodes.length||r.removedNodes.length))schedule()}).observe(node,{childList:true,subtree:true})}
document.addEventListener('click',schedule);document.addEventListener('change',schedule);window.addEventListener('hashchange',schedule);schedule();
})();
