const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}, set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function view(id){$$('.view').forEach(x=>x.classList.toggle('show',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
$$('nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('.jump').forEach(b=>b.onclick=()=>view(b.dataset.target));
const ideas=['make a button that looks way too dramatic','add three pretend business cards','draw a logo with one color','change one CSS variable yourself','beat your memory score twice','add a weird emoji card','rename one section in index.html'];
$('#ideaBtn').onclick=()=>$('#idea').textContent='Try this: '+ideas[Math.floor(Math.random()*ideas.length)]+'.';
$$('.chips button').forEach(b=>b.onclick=()=>{$('#vibe').textContent=b.textContent.split(' ')[0]});$('#curiosity').oninput=e=>$('#curiosityLabel').textContent=e.target.value+'%';
const th=get('theme','purple');if(th!=='purple')document.body.dataset.theme=th;$$('.themes button').forEach(b=>b.onclick=()=>{let t=b.dataset.theme;document.body.dataset.theme=t==='purple'?'':t;set('theme',t);toast(t+' theme loaded')});
function btn(){let r=$('#radius').value,s=$('#shadow').value,t=$('#btnText').value||'BUTTON',b=$('#madeBtn');b.textContent=t;b.style.borderRadius=r+'px';b.style.boxShadow=`0 ${Math.max(4,s/2)}px ${s}px #7c3aed55`;$('#code').textContent=`.my-button {\n  border-radius: ${r}px;\n  box-shadow: 0 ${Math.max(4,s/2)}px ${s}px rgba(124,58,237,.35);\n  background: linear-gradient(135deg, var(--p), var(--s));\n}`};['#radius','#shadow','#btnText'].forEach(s=>$(s).oninput=btn);btn();
let cards=get('cards',[{t:'Tiny Experiment',e:'🧪'},{t:'Click Me Later',e:'🛼'}]);function cardsRender(){let s=$('#cardStage');s.innerHTML='';cards.forEach((c,i)=>{let d=document.createElement('div');d.className='made-card';d.innerHTML=`<button>×</button><div class="emoji">${c.e}</div><b>${c.t}</b>`;d.querySelector('button').onclick=()=>{cards.splice(i,1);set('cards',cards);cardsRender()};s.appendChild(d)})}$('#addCard').onclick=()=>{let t=$('#cardTitle').value.trim();if(!t)return;cards.push({t,e:$('#cardEmoji').value||'✨'});set('cards',cards);cardsRender();toast('Card added')};cardsRender();
const cv=$('#doodle'),ctx=cv.getContext('2d');let draw=false,last;function p(e){let r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*cv.width/r.width,y:(e.clientY-r.top)*cv.height/r.height}}cv.onpointerdown=e=>{draw=true;last=p(e)};cv.onpointermove=e=>{if(!draw)return;let q=p(e);ctx.strokeStyle=$('#pen').value;ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(q.x,q.y);ctx.stroke();last=q};cv.onpointerup=()=>draw=false;$('#clearCanvas').onclick=()=>ctx.clearRect(0,0,cv.width,cv.height);
let timer,ready=false,start=0;$('#reactionStart').onclick=()=>{ready=false;$('#reactionBox').className='reaction wait';$('#reactionBox').textContent='Wait...';clearTimeout(timer);timer=setTimeout(()=>{ready=true;start=performance.now();$('#reactionBox').className='reaction ready';$('#reactionBox').textContent='CLICK NOW!'},1200+Math.random()*2500)};$('#reactionBox').onclick=()=>{if(!ready){clearTimeout(timer);$('#reactionBox').className='reaction bad';$('#reactionBox').textContent='Too soon 😭';return}let ms=Math.round(performance.now()-start);ready=false;$('#reactionBox').className='reaction';$('#reactionBox').textContent=ms+' ms';let best=get('reactBest',null);if(best===null||ms<best){best=ms;set('reactBest',best)};$('#reactionBest').textContent='Best: '+best+' ms'};let rb=get('reactBest',null);$('#reactionBest').textContent=rb?'Best: '+rb+' ms':'Best: —';
const phrases=['Colorful code is still code.','Tiny experiments build big confidence.','I can break it because I can fix it.','Today I am clicking first and overthinking later.'];let phrase=phrases[0];$('#newPhrase').onclick=()=>{phrase=phrases[Math.floor(Math.random()*phrases.length)];$('#phrase').textContent=phrase;$('#typing').value=''};$('#typing').oninput=e=>{$('#typingScore').textContent=e.target.value.length+' characters';if(e.target.value===phrase)toast('Perfect match!')};
const em=['🍉','🎸','🦋','🚀','🍩','🎨','💎','🌈'];let mem=[],open=[],moves=0,lock=false;function newMem(){mem=[...em,...em].sort(()=>Math.random()-.5).map((e,i)=>({e,m:false}));open=[];moves=0;lock=false;memRender()}function memRender(){let g=$('#memory');g.innerHTML='';mem.forEach((c,i)=>{let b=document.createElement('button');b.textContent=(open.includes(i)||c.m)?c.e:'?';b.className=(open.includes(i)?'open ':'')+(c.m?'matched':'');b.onclick=()=>flip(i);g.appendChild(b)});$('#moves').textContent='Moves: '+moves;let best=get('memBest',null);$('#memoryBest').textContent=best?'Best: '+best:'Best: —'}function flip(i){if(lock||open.includes(i)||mem[i].m)return;open.push(i);memRender();if(open.length===2){moves++;lock=true;let[a,b]=open;if(mem[a].e===mem[b].e){mem[a].m=mem[b].m=true;open=[];lock=false;setTimeout(()=>{if(mem.every(x=>x.m)){let best=get('memBest',null);if(best===null||moves<best)set('memBest',moves);toast('You won!')}memRender()},250)}else setTimeout(()=>{open=[];lock=false;memRender()},650)}}$('#resetMemory').onclick=newMem;newMem();
let notes=get('notes',[{t:'Change one CSS rule just to see what happens.',c:'yellow',r:'-1deg'},{t:'Future idea: fake coffee shop site.',c:'pink',r:'1deg'}]);function noteRender(){let w=$('#wall');w.innerHTML='';notes.forEach((n,i)=>{let d=document.createElement('div');d.className='sticky '+n.c;d.style.setProperty('--tilt',n.r);d.innerHTML=`<button>×</button><p>${n.t.replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}</p>`;d.querySelector('button').onclick=()=>{notes.splice(i,1);set('notes',notes);noteRender()};w.appendChild(d)})}$('#addNote').onclick=()=>{let t=$('#noteText').value.trim();if(!t)return;notes.unshift({t,c:$('#noteColor').value,r:(Math.random()*4-2).toFixed(1)+'deg'});$('#noteText').value='';set('notes',notes);noteRender()};noteRender();
$('#surprise').onclick=()=>{view(['lab','games','notes'][Math.floor(Math.random()*3)]);toast('Surprise mode activated!')};$('#resetAll').onclick=()=>{if(confirm('Reset all saved PlayLab data?')){localStorage.clear();location.reload()}};
