/* Merrywheel: world data — families, streets, lessons, archive */
'use strict';

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const MDAYS = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

const FAMILIES = [
  { m: 0, name: 'The Januarys', color: '#7fa7c9', accent: '#e8eef6', host: 'Grandpa January',
    traits: 'Fresh starts, big plans, and very early mornings. They write resolutions for everybody, whether you asked or not.',
    lines: ['New year, new you. I wrote you a list. It is only forty items long.', 'The parade starts at dawn. We will be marching whether the sun is up or not.', 'December throws a good party. We clean up after it. Somebody has to.'] },
  { m: 1, name: 'The Februarys', color: '#d97a93', accent: '#fbe4ea', host: 'Little Miss February',
    traits: 'The baby of the families and the shortest of them all. Every four years they get a bonus child and act like royalty about it.',
    lines: ['I may be the shortest month, but I have the most hearts. Count them.', 'Leap Day is coming. My little brother Twenty-Nine will be insufferable.', 'Everyone forgets about me. Then I give them chocolate and they remember.'] },
  { m: 2, name: 'The Marches', color: '#6fae6a', accent: '#e6f3e2', host: 'Captain March',
    traits: 'Blustery, lucky, and hard-working. They come in like a lion and go out like a lamb, and they will tell you so.',
    lines: ['In like a lion. Out like a lamb. Mind the wind on your way in.', 'Luck is lovely. Hard work grows the food. We honor both.', 'Ever found a four-leaf clover? I have found nine. I am not bragging. Nine.'] },
  { m: 3, name: 'The Aprils', color: '#9ec7e6', accent: '#eaf5fb', host: 'Cousin April',
    traits: 'They cannot be trusted. Sunshine one minute, storm the next, and they think it is hilarious.',
    lines: ['Lovely day for an egg hunt. Probably. Bring an umbrella. Or don\'t. Surprise.', 'April showers bring May flowers. The Mays never say thank you.', 'I told the Seconds it was naptime. They believed me for one whole second.'] },
  { m: 4, name: 'The Mays', color: '#e8a3c4', accent: '#fcebf3', host: 'Mama May',
    traits: 'Flowers, fiestas, and honor. The busiest family in spring, and the first to bring you a casserole.',
    lines: ['Did you call your mother? Call your mother.', 'Three holidays in one month. Do not ask how we do it. Coffee.', 'We dance at the fiesta, we bring flowers to the mothers, and we remember the fallen. All of it matters.'] },
  { m: 5, name: 'The Junes', color: '#e9a23b', accent: '#fdf0d8', host: 'Uncle June',
    traits: 'Cookout headquarters. Long days, longer tables, and a grill that never cools down.',
    lines: ['Pull up a chair. There\'s always room at the cookout.', 'Freedom is worth celebrating out loud, with family, every single year.', 'I have been working this grill since sunrise. Best day of my life.'] },
  { m: 6, name: 'The Julys', color: '#d24a4a', accent: '#fde3e3', host: 'Big Jim July',
    traits: 'Loud, proud, and obsessed with fireworks. They have a fireworks budget. It is bigger than the village fund.',
    lines: ['FIREWORKS. That is the whole sentence.', 'You hear that boom? That was a test. The real show is louder.', 'The Decembers think their lights are bright. Cute.'] },
  { m: 7, name: 'The Augusts', color: '#c9a227', accent: '#fbf3d6', host: 'Lady August',
    traits: 'The honored ones. They host the Jubilee, when all twelve families set aside their squabbles and the children of time put on a show.',
    lines: ['Welcome, dear. Every family is welcome at the Pavilion. Even the Julys, if they keep the volume down.', 'Once a year, the months stop arguing about who is most important. It is the most peaceful night of the year.', 'Friendship first. Then the Jubilee. Then, perhaps, a nap.'] },
  { m: 8, name: 'The Septembers', color: '#b0703a', accent: '#f6e6d6', host: 'Professor September',
    traits: 'Dignified and organized. Sharpened pencils, pressed shirts, and a deep respect for honest work and for remembering.',
    lines: ['Back to school, back to work, back to order. Lovely.', 'We honor the workers who built everything you see.', 'Some days are for celebrating. Some are for remembering. We keep both well.'] },
  { m: 9, name: 'The Octobers', color: '#e0702a', accent: '#fde8d8', host: 'Count October',
    traits: 'Theatrical weirdos who wear costumes in March just because. Spooky, yes, but with substance.',
    lines: ['Do you like my cape? I wear it to the dentist.', 'Before the spooky season, we honor the first peoples of this land. That comes first.', 'Boo. Sorry. Reflex.'] },
  { m: 10, name: 'The Novembers', color: '#9a5a2e', accent: '#f4e3d4', host: 'Granny November',
    traits: 'They feed everybody. Gratitude, honor, and enough pie to bury a small village.',
    lines: ['Have you eaten? You look like you haven\'t eaten. Sit down.', 'We thank our veterans first, then we feast. That is the November way.', 'Sweet potato pie. Two slices. Don\'t argue with me.'] },
  { m: 11, name: 'The Decembers', color: '#2f7a55', accent: '#e2f2e9', host: 'Papa December',
    traits: 'Warm and generous. They throw the big year-end bash and hand out gifts to people they met that morning.',
    lines: ['There you are. I saved you a cocoa. And a cookie. And a sweater.', 'The Eve party is ours. The Januarys can have the morning. They like mornings.', 'Every light on Twinkle Lane is for somebody. One of them is for you.'] },
];

/* lesson types: order (steps in order), paint (copy a design), find (hidden items), timing (catch at the right moment),
   clock (stop the countdown at midnight), reflect (quiet, respectful participation) */
const STREETS = [
  { id: 'firstlight', m: 0, d: 1, name: 'First Light Avenue', holiday: "New Year's Day", img: 'firstlight',
    facts: ['The Januarys lead the New Year\'s Day parade at dawn: marching bands, floats, and a lot of yawning.', 'Folks write resolutions, small promises to themselves for the year ahead, and pin them to the Resolution Wall.', 'In the South, black-eyed peas and collard greens on New Year\'s Day are said to bring luck and money. Cornbread on the side is not optional.'],
    lessons: [{ type: 'order', name: 'Lucky Black-Eyed Peas', item: 'Pot of Lucky Peas', price: 12, steps: ['Soak the black-eyed peas overnight', 'Brown onions and a little smoked turkey in the pot', 'Add the peas and cover with broth', 'Simmer low and slow until tender', 'Stir in the collard greens', 'Serve with a wedge of cornbread'] }] },
  { id: 'dream', m: 0, d: 19, name: 'Dream Boulevard', holiday: 'Martin Luther King Jr. Day', img: 'dream', solemn: true,
    facts: ['Dr. Martin Luther King Jr. led the American civil rights movement with nonviolence, courage, and words that still move people.', 'His holiday falls on the third Monday of January, near his birthday on January 15. It is observed as a national day of service: "a day on, not a day off."', 'He asked, "Life\'s most persistent and urgent question is: what are you doing for others?"'],
    lessons: [{ type: 'reflect', name: 'A Day of Service', actions: [['Pack a meal box for a neighbor', 'You fill a box with soup, bread, and a handwritten note.'], ['Read a story to the little Minutes', 'They sit still for almost a whole minute. A record.'], ['Hang your dream on the Dream Wall', 'Your dream joins hundreds of others, fluttering in the wind.']], ask: 'What is one dream you have for your community?' }] },
  { id: 'sweetheart', m: 1, d: 14, name: 'Sweetheart Street', holiday: "Valentine's Day", img: 'sweetheart',
    facts: ['Valentine\'s Day is for every kind of love: sweethearts, friends, family, and neighbors.', 'Handmade cards have been a tradition for hundreds of years. Lace, ribbon, and a little glue go a long way.', 'The Februarys hand out more chocolate on this one day than on all their other days combined.'],
    lessons: [{ type: 'paint', name: 'Handmade Valentine Card', item: 'Valentine Card', price: 8, shape: 'heart', palette: ['#c8344f', '#f2a7b8', '#fbeff2', '#8a2a3d', '#e2b04a'] }] },
  { id: 'founders', m: 1, d: 16, name: "Founders' Avenue", holiday: "Presidents' Day", img: 'founders',
    facts: ['Presidents\' Day falls on the third Monday in February, between George Washington\'s birthday (February 22) and Abraham Lincoln\'s (February 12).', 'There is an old legend that young George Washington chopped down a cherry tree and said, "I cannot tell a lie." It is probably just a story, but the cherry pie is real.', 'The Februarys host it on Founders\' Avenue with history walks and the Great Cherry Pie Contest.'],
    lessons: [{ type: 'order', name: 'Cherry Pie', item: 'Cherry Pie', price: 14, steps: ['Roll out the bottom crust', 'Toss cherries with sugar and a little cornstarch', 'Pour the filling into the crust', 'Weave a lattice top', 'Brush the crust with egg wash', 'Bake until golden and bubbling'] }] },
  { id: 'shamrock', m: 2, d: 17, name: 'Shamrock Street', holiday: "St. Patrick's Day", img: 'shamrock',
    facts: ['St. Patrick\'s Day honors Ireland\'s patron saint, and today it is a worldwide celebration of Irish culture.', 'Legend says St. Patrick used the three-leaf shamrock to teach. A four-leaf clover is rare and said to be lucky.', 'Wear green, or the Marches will pinch you. Gently. Mostly.'],
    lessons: [{ type: 'find', name: 'Four-Leaf Clover Hunt', item: 'Lucky Clover Charm', price: 10, target: 'four-leaf clover', count: 5, decoy: 'clover', theme: 'clover' }] },
  { id: 'harvestheroes', m: 2, d: 31, name: 'Harvest Heroes Lane', holiday: 'César Chávez Day', img: 'harvestheroes', solemn: true,
    facts: ['César Chávez was a labor leader who, with Dolores Huerta, organized farmworkers to win fair pay and safer working conditions.', 'His birthday, March 31, is honored as a day of service and learning. His motto was "Sí, se puede": yes, it can be done.', 'Nearly every fruit and vegetable we eat was picked by someone\'s hands. This lane thanks them.'],
    lessons: [{ type: 'order', name: 'Plant a Vegetable Row', item: 'Basket of Fresh Vegetables', price: 12, steps: ['Loosen the soil with a hoe', 'Mix in compost', 'Dig a straight furrow', 'Drop seeds a hand-width apart', 'Cover gently with soil', 'Water slowly at the roots'] }] },
  { id: 'springmeadow', m: 3, d: 5, name: 'Spring Meadow Lane', holiday: 'Easter', img: 'springmeadow',
    facts: ['Easter is a Christian holiday celebrating the resurrection of Jesus, and in spring it also means new life everywhere.', 'Egg hunts and dyed eggs are beloved traditions. Eggs stand for new beginnings.', 'The Aprils host the egg hunt. It rains about half the time. They love that.'],
    lessons: [{ type: 'find', name: 'Spring Egg Hunt', item: 'Basket of Painted Eggs', price: 10, target: 'egg', count: 8, theme: 'eggs', rain: true },
              { type: 'paint', name: 'Dye an Easter Egg', item: 'Dyed Egg', price: 6, shape: 'egg', palette: ['#9ec7e6', '#f2c2d4', '#f5e08a', '#a8d5a2', '#c7a6e0'] }] },
  { id: 'fiesta', m: 4, d: 5, name: 'Fiesta Street', holiday: 'Cinco de Mayo', img: 'fiesta',
    facts: ['Cinco de Mayo remembers the Mexican army\'s victory at the Battle of Puebla on May 5, 1862. (Mexican Independence Day is a different day: September 16.)', 'Today it is a celebration of Mexican culture, with mariachi music, folk dancing, and food.', 'Papel picado, delicate cut-paper banners, flutter over the street in every color.'],
    lessons: [{ type: 'paint', name: 'Papel Picado Banner', item: 'Papel Picado Banner', price: 10, shape: 'flags', palette: ['#e0457b', '#2fa3c9', '#f2c230', '#5cb85c', '#f07f2a'] }] },
  { id: 'blossom', m: 4, d: 10, name: 'Blossom Boulevard', holiday: "Mother's Day", img: 'blossom',
    facts: ['Mother\'s Day in the United States falls on the second Sunday in May. Anna Jarvis started it in 1908 to honor her own mother.', 'It honors mothers, grandmothers, aunties, and everyone who mothers someone.', 'Bouquets, breakfast in bed, and phone calls home. Mama May checks.'],
    lessons: [{ type: 'order', name: 'Arrange a Bouquet', item: 'Spring Bouquet', price: 12, steps: ['Trim the stems at an angle', 'Strip leaves below the waterline', 'Start with the biggest blooms in the center', 'Add smaller flowers around them', 'Tuck in greenery to fill the gaps', 'Tie with a ribbon and add a note'] }] },
  { id: 'honor', m: 4, d: 25, name: 'Honor Avenue', holiday: 'Memorial Day', img: 'honor', solemn: true,
    facts: ['Memorial Day, the last Monday in May, honors the men and women who died while serving in the U.S. military.', 'At 3:00 p.m. local time, Americans are asked to pause for a National Moment of Remembrance.', 'The red poppy is a symbol of remembrance, inspired by the poem "In Flanders Fields."'],
    lessons: [{ type: 'reflect', name: 'Moment of Remembrance', actions: [['Place a small flag by the memorial', 'The row of flags moves together in the breeze.'], ['Fold a paper poppy', 'You set the red poppy among the others.'], ['Pause for a moment of silence', null]] }] },
  { id: 'freedom', m: 5, d: 19, name: 'Freedom Street', holiday: 'Juneteenth', img: 'freedom',
    facts: ['On June 19, 1865, Union troops arrived in Galveston, Texas, and announced that enslaved people there were free, more than two years after the Emancipation Proclamation.', 'Juneteenth has been celebrated in Black communities for over 150 years and became a federal holiday in 2021.', 'Traditions include cookouts, readings of the Emancipation Proclamation, family reunions, and red foods and drinks, like red velvet cake and strawberry soda, honoring resilience.'],
    lessons: [{ type: 'order', name: 'Red Velvet Cake', item: 'Red Velvet Cake', price: 16, steps: ['Whisk flour, cocoa, and a pinch of salt', 'Beat butter and sugar until fluffy', 'Add eggs, buttermilk, and red coloring', 'Fold the dry into the wet', 'Bake in two round pans', 'Frost with cream cheese icing'] }] },
  { id: 'backyard', m: 5, d: 21, name: 'Backyard Boulevard', holiday: "Father's Day", img: 'backyard',
    facts: ['Father\'s Day falls on the third Sunday in June. It honors fathers, granddads, uncles, and father figures.', 'Uncle June runs cookout headquarters. Nobody touches the grill without permission.', 'Ties, tools, and terrible jokes are the traditional gifts. The jokes are free.'],
    lessons: [{ type: 'timing', name: 'Grill Master', item: 'Cookout Plate', price: 12, theme: 'grill', count: 10 }] },
  { id: 'liberty', m: 6, d: 4, name: 'Liberty Boardwalk', holiday: 'Independence Day', img: 'liberty',
    facts: ['On July 4, 1776, the Declaration of Independence was adopted, and the United States was born.', 'Fireworks, parades, and picnics have marked the Fourth since the very first anniversary in 1777.', 'The Julys have a fireworks budget. Nobody knows how big it is. It is very big.'],
    lessons: [{ type: 'timing', name: 'Fireworks Show', item: 'Sparkler Bundle', price: 10, theme: 'fireworks', count: 12 }] },
  { id: 'friendship', m: 7, d: 2, name: 'Friendship Lane', holiday: 'Friendship Day', img: 'friendship',
    facts: ['Friendship Day is celebrated on the first Sunday of August in many countries, and the United Nations marks it on July 30.', 'Friends trade bracelets made of knotted thread. You wear it until it falls off on its own.', 'The Augusts say a good friend is worth more than a good holiday. Then they host both.'],
    lessons: [{ type: 'order', name: 'Friendship Bracelet', item: 'Friendship Bracelet', price: 8, steps: ['Cut six strands of embroidery thread', 'Knot them together at the top', 'Tape the knot to the table', 'Tie forward knots, left to right', 'Repeat row after row', 'Tie it on a friend\'s wrist'] }] },
  { id: 'pavilion', m: 7, d: 20, name: 'The Grand Pavilion', holiday: 'The August Jubilee', img: 'pavilion', jubilee: true,
    facts: ['Once a year, all twelve families gather at the Grand Pavilion for the August Jubilee.', 'The months set aside their squabbles about who is most important. For one night, nobody argues. (The Julys argue a little.)', 'All of time\'s children put on a show: the Seconds, Minutes, Hours, Days, and Weeks.'],
    lessons: [{ type: 'timing', name: 'Catch the Falling Stars', item: 'Jubilee Star', price: 14, theme: 'stars', count: 12 }] },
  { id: 'workers', m: 8, d: 7, name: "Workers' Way", holiday: 'Labor Day', img: 'workers',
    facts: ['Labor Day, the first Monday in September, honors working people and the labor movement that won the weekend and the eight-hour day.', 'The first Labor Day parade marched in New York City in 1882. It became a national holiday in 1894.', 'The Septembers celebrate with a parade of every trade in the village, and then everybody takes the day off. Properly.'],
    lessons: [{ type: 'order', name: 'Build a Birdhouse', item: 'Handmade Birdhouse', price: 15, steps: ['Measure and mark the boards', 'Cut the front, back, sides, and roof', 'Drill the entrance hole', 'Nail the walls together', 'Attach the roof', 'Sand the edges smooth'] }] },
  { id: 'remembrance', m: 8, d: 11, name: 'Remembrance Row', holiday: 'Patriot Day', img: 'remembrance', solemn: true,
    facts: ['On September 11, 2001, nearly 3,000 people were killed in attacks on the United States.', 'Patriot Day honors those lost and the first responders who ran toward danger to help others.', 'It is also a National Day of Service and Remembrance. Many people volunteer in their memory.'],
    lessons: [{ type: 'reflect', name: 'We Remember', actions: [['Light a candle on the wall', 'Your candle joins a long row of small flames.'], ['Leave a thank-you note at the firehouse', 'A firefighter reads it and nods.'], ['Pause for a moment of silence', null]] }] },
  { id: 'heritage', m: 9, d: 12, name: 'Heritage Trail', holiday: "Indigenous Peoples' Day", img: 'heritage', solemn: true,
    facts: ['Indigenous Peoples\' Day, the second Monday in October, honors the histories, cultures, and contributions of Native American peoples.', 'Many Native nations planted the "Three Sisters" together: corn, beans, and squash. Each one helps the others grow.', 'The corn gives the beans a pole to climb, the beans feed the soil, and the wide squash leaves keep weeds away.'],
    lessons: [{ type: 'order', name: 'Plant the Three Sisters', item: 'Three Sisters Harvest', price: 14, steps: ['Build a small mound of soil', 'Plant corn seeds in the center', 'Wait until the corn is a hand tall', 'Plant beans around the corn', 'Plant squash around the edge of the mound', 'Let them grow together'] }] },
  { id: 'haunted', m: 9, d: 31, name: 'Haunted Hollow', holiday: 'Halloween', img: 'haunted',
    facts: ['Halloween grew from the old Celtic festival of Samhain, when people lit bonfires and wore costumes as the nights grew long.', 'Trick-or-treating, jack-o\'-lanterns, and costume parades are favorite traditions.', 'The Octobers have been in costume since March. Nobody has seen their real faces in years.'],
    lessons: [{ type: 'paint', name: 'Costume Mask', item: 'Costume Mask', price: 10, shape: 'mask', palette: ['#e0702a', '#6b3fa0', '#1f1f2e', '#7bc24a', '#f2e6c8'] },
              { type: 'order', name: 'Candy Apples', item: 'Candy Apples', price: 9, steps: ['Wash and dry the apples', 'Push a stick into each apple', 'Boil sugar, water, and corn syrup', 'Stir in the red coloring', 'Dip and twirl each apple', 'Set them on parchment to harden'] }] },
  { id: 'valor', m: 10, d: 11, name: 'Valor Street', holiday: 'Veterans Day', img: 'valor', solemn: true,
    facts: ['Veterans Day, November 11, honors everyone who has served in the U.S. armed forces, living and gone.', 'It began as Armistice Day, marking the end of World War I fighting at the 11th hour of the 11th day of the 11th month, 1918.', 'The simplest tradition is the most important: say thank you to a veteran.'],
    lessons: [{ type: 'reflect', name: 'Thank a Veteran', actions: [['Hang a flag on the hall', 'The flag lifts in the morning wind.'], ['Pack a care package', 'Socks, coffee, and a handwritten card.'], ['Write a thank-you letter', 'The Veterans Hall will deliver it.']], ask: 'Write a few words of thanks to a veteran.' }] },
  { id: 'harvestsq', m: 10, d: 26, name: 'Harvest Square', holiday: 'Thanksgiving', img: 'harvestsq',
    facts: ['Thanksgiving, the fourth Thursday in November, is a day of gratitude, family, and far too much food.', 'Many families go around the table and say what they are thankful for.', 'Granny November feeds the whole village at one long table. Sweet potato pie is mandatory.'],
    lessons: [{ type: 'order', name: 'Sweet Potato Pie', item: 'Sweet Potato Pie', price: 14, steps: ['Boil the sweet potatoes until soft', 'Mash them smooth with butter', 'Mix in sugar, eggs, milk, and nutmeg', 'Pour the filling into a pie crust', 'Bake until the center sets', 'Cool it before you slice. Granny insists.'] }] },
  { id: 'twinkle', m: 11, d: 25, name: 'Twinkle Lane', holiday: 'Christmas', img: 'twinkle',
    facts: ['Christmas celebrates the birth of Jesus and is also a season of giving, lights, and family.', 'Evergreen wreaths, round with no beginning and no end, stand for everlasting life and hope.', 'The Decembers wrap gifts for people they met that morning. It is their whole personality.'],
    lessons: [{ type: 'paint', name: 'Evergreen Wreath', item: 'Christmas Wreath', price: 14, shape: 'wreath', palette: ['#2f7a55', '#c8344f', '#e2b04a', '#f4efe4', '#1f4f3a'] },
              { type: 'order', name: 'Gift Wrapping', item: 'Wrapped Gift', price: 10, steps: ['Measure paper to fit around the box', 'Cut it with a little extra', 'Fold the sides over and tape', 'Fold the ends into neat triangles', 'Tie the ribbon in a bow', 'Add a tag with a name'] }] },
  { id: 'countdown', m: 11, d: 31, name: 'Countdown Court', holiday: "New Year's Eve", img: 'countdown',
    facts: ['On New Year\'s Eve, people everywhere count down the last ten seconds of the year together.', 'Many cities drop a glowing ball at midnight. New York\'s Times Square ball drop began in 1907.', 'The Eve party belongs to the Decembers. The morning after belongs to the Januarys. Everyone agrees on that, at least.'],
    lessons: [{ type: 'clock', name: 'Midnight Countdown', item: 'Noisemaker', price: 8 }] },
];

const LANTERN = [
  { id: 'diwali', m: 10, d: 8, name: 'Diya Lane', holiday: 'Diwali', img: 'diwali', world: true,
    facts: ['Diwali, the festival of lights, is celebrated by Hindus, Sikhs, Jains, and some Buddhists. It honors the victory of light over darkness.', 'Families light rows of small clay oil lamps called diyas and draw colorful rangoli patterns at their doors.', 'Its date follows the lunar calendar, usually in October or November.'],
    lessons: [{ type: 'paint', name: 'Paint a Diya', item: 'Painted Diya', price: 10, shape: 'diya', palette: ['#e2702a', '#f2c230', '#c8344f', '#2fa3a0', '#6b3fa0'] }] },
  { id: 'lunar', m: 1, d: 17, name: 'Red Lantern Street', holiday: 'Lunar New Year', img: 'lunar', world: true,
    facts: ['Lunar New Year is celebrated across East and Southeast Asia and around the world. Each year is named for one of twelve zodiac animals.', 'Red stands for luck. Families hang red lanterns, give red envelopes, and gather for a reunion dinner.', 'Dumplings are folded to look like old gold ingots, for a prosperous year.'],
    lessons: [{ type: 'order', name: 'Fold Dumplings', item: 'Plate of Dumplings', price: 12, steps: ['Mix the filling of cabbage, ginger, and scallion', 'Place a spoonful in a wrapper', 'Wet the edge with water', 'Fold and pleat it closed', 'Steam until tender', 'Serve with dipping sauce'] }] },
  { id: 'eid', m: 2, d: 20, name: 'Crescent Court', holiday: 'Eid al-Fitr', img: 'eid', world: true,
    facts: ['Eid al-Fitr marks the end of Ramadan, the Muslim month of fasting from dawn to sunset.', 'It begins with the sighting of the new crescent moon, morning prayers, new clothes, and visiting family.', 'Giving to people in need before Eid prayers, called zakat al-fitr, is part of the celebration.'],
    lessons: [{ type: 'order', name: "Ma'amoul Cookies", item: "Ma'amoul Cookies", price: 12, steps: ['Rub butter into semolina', 'Rest the dough overnight', 'Roll date paste into small balls', 'Wrap the dough around each date ball', 'Press each cookie into a carved mold', 'Bake, then dust with powdered sugar'] }] },
  { id: 'hanukkah', m: 11, d: 4, name: 'Menorah Mews', holiday: 'Hanukkah', img: 'hanukkah', world: true,
    facts: ['Hanukkah, the Jewish festival of lights, lasts eight nights. It remembers the rededication of the Temple in Jerusalem.', 'The story says a single day of oil burned for eight days. Families light one more candle on the menorah each night.', 'Foods fried in oil, like latkes and jelly doughnuts, honor the miracle. Kids spin the dreidel.'],
    lessons: [{ type: 'order', name: 'Crispy Latkes', item: 'Plate of Latkes', price: 11, steps: ['Grate potatoes and an onion', 'Squeeze out all the liquid', 'Mix in egg, flour, and salt', 'Heat oil in a skillet', 'Fry spoonfuls until golden on both sides', 'Serve with applesauce and sour cream'] }] },
  { id: 'kwanzaa', m: 11, d: 26, name: 'Kinara Commons', holiday: 'Kwanzaa', img: 'kwanzaa', world: true,
    facts: ['Kwanzaa, December 26 through January 1, celebrates African American culture and heritage. It was created by Dr. Maulana Karenga in 1966.', 'Each of the seven days honors one principle, such as Umoja (unity) and Kuumba (creativity).', 'The kinara holds seven candles: three red on the left, one black in the center, and three green on the right.'],
    lessons: [{ type: 'order', name: 'Set the Kinara', item: 'Handmade Kinara', price: 14, steps: ['Place the black candle in the center (Umoja)', 'Place the first red candle, left of center', 'Place the first green candle, right of center', 'Add the second red and second green', 'Add the outer red and outer green', 'Set the kinara on the mkeka mat'] }] },
];

const ALL_STREETS = [...STREETS, ...LANTERN];

const ARCHIVE = [
  ['January 15', 'Dr. King\'s Birthday', 'The day his holiday was built around.'], ['February', 'Black History Month', 'A month to learn and honor Black history.'],
  ['February 2', 'Groundhog Day', 'If he sees his shadow, six more weeks of winter. The Februarys bribe him.'], ['Late Feb/Mar', 'Mardi Gras', 'Beads, king cake, and brass bands before Lent.'],
  ['March', "Women's History Month", 'Honoring the women who shaped history.'], ['March 14', 'Pi Day', '3.14, celebrated with pie, naturally.'],
  ['April 15', 'Titanic Remembrance', 'Remembering the great ship and the 1,500 souls lost in 1912.'], ['April 22', 'Earth Day', 'Plant a tree, pick up litter, love the planet.'],
  ['Last Fri in April', 'Arbor Day', 'A day for planting trees.'], ['June 14', 'Flag Day', 'Honoring the adoption of the U.S. flag in 1777.'],
  ['Sept 15 to Oct 15', 'Hispanic Heritage Month', 'Celebrating Hispanic and Latino Americans.'], ['September 9', 'National Teddy Bear Day', 'Hug a bear. Any bear. The softer the better.'],
  ['Sunday after Labor Day', "Grandparents' Day", 'For the grandmas, granddads, and Big Mamas.'], ['November 1 to 2', 'Día de los Muertos', 'Families build ofrendas to remember loved ones with marigolds and photos.'],
  ['November 13', 'World Kindness Day', 'Do one kind thing. Then another.'], ['December 4', 'National Cookie Day', 'The most important holiday, according to some.'],
  ['December 21', 'Winter Solstice', 'The longest night, and the return of the light.'], ['February 29', 'Leap Day', 'The Februarys\' bonus child. He will not let you forget it.'],
];

const UPGRADES = [
  { id: 'lights', name: 'String Lights', cost: 60, desc: 'Lights strung across the plaza.' },
  { id: 'fountain', name: 'Plaza Fountain', cost: 120, desc: 'A fountain with twelve spouts, one per family.' },
  { id: 'banners', name: 'Family Banners', cost: 180, desc: 'Twelve banners in the family colors.' },
  { id: 'lantern', name: 'Open the Lantern Quarter', cost: 220, desc: 'A new district for Diwali, Lunar New Year, Eid, Hanukkah, and Kwanzaa.' },
  { id: 'clock', name: 'Clock Tower', cost: 300, desc: 'Time\'s children love it. The Seconds climb it.' },
  { id: 'gardens', name: 'Flower Gardens', cost: 380, desc: 'Gardens around the plaza ring.' },
  { id: 'carousel', name: 'Carousel', cost: 480, desc: 'Twelve carved animals, one per month.' },
  { id: 'wheel', name: 'Ferris Wheel', cost: 620, desc: 'You can see every district from the top.' },
];

const DAYS = [
  ['Sunday', 'just wants a nap. "Wake me up for dinner. Or don\'t."'], ['Monday', 'is grumpy. "Don\'t talk to me until I\'ve had my coffee. Or after."'],
  ['Tuesday', 'is quietly reliable. "Somebody has to be the second day. I don\'t mind."'], ['Wednesday', 'is stuck in the middle. "Halfway there. Hump day. Please stop saying hump day."'],
  ['Thursday', 'is almost excited. "Almost Friday. Almost. Don\'t jinx it."'], ['Friday', 'is the life of the party. "Party at my place. Everybody\'s invited. Even Monday."'],
  ['Saturday', 'is pure freedom. "No schedule. No alarms. Just cartoons and pancakes."'],
];

/* The months love arguing about who is most important.
   lines: [speaker, text]  speaker 'a' | 'b' | 'x' (narration)  ·  wise: the answer that makes peace */
const ARGUMENTS = [
  { id: 'newyear', a: 11, b: 0, title: "Who owns New Year's?",
    lines: [['a', 'The countdown is ours. Midnight happens in December. Technically.'], ['b', 'Midnight is the first second of January. Technically-er.'], ['a', 'We throw the party.'], ['b', 'We clean it up. Who do you think finds confetti in the couch cushions until March?']],
    wise: "The Eve is December's party and the morning is January's parade. You need each other." },
  { id: 'toosoon', a: 10, b: 11, title: 'Too soon for Christmas?',
    lines: [['a', 'There is a TREE on Twinkle Lane. It is November the third.'], ['b', "It's festive."], ['a', 'We have not even carved the turkey. Respect the pie.'], ['b', 'The lights are already up. Taking them down would be sad.']],
    wise: 'Thanksgiving first, then the lights. Being grateful makes the giving mean more.' },
  { id: 'flowers', a: 3, b: 4, title: 'Who gets credit for the flowers?',
    lines: [['a', "April showers bring May flowers. That's science. You're welcome."], ['b', 'We plant them, water them, and arrange them. Showers just... happen.'], ['a', '"Just happen"? I work very hard at being unpredictable.'], ['b', 'You rained on my tulips sideways.']],
    wise: 'No rain, no flowers. No flowers, no point to the rain. You are a team.' },
  { id: 'lights', a: 6, b: 11, title: 'Who has the brightest lights?',
    lines: [['a', 'FIREWORKS. In the SKY. You can see them three villages over.'], ['b', 'Twinkle lights. Every window. Every night for a month. Yours last four seconds.'], ['a', 'The best four seconds of the year.'], ['b', 'We have a light-up reindeer. It waves.']],
    wise: 'One lights up the sky for a moment, one lights up the windows all month. Both bring people outside together.' },
  { id: 'shortest', a: 1, b: 0, title: "Size isn't everything",
    lines: [['a', "We may be the shortest, but we have Valentine's AND Presidents' Day."], ['b', 'We have thirty-one days. Thirty-one.'], ['a', 'And every four years we get a bonus child. Twenty-Nine, wave.'], ['x', 'Twenty-Nine waves from his tiny throne. "I am royalty," he announces.']],
    wise: "It's not how many days you have. It's what you do with them." },
  { id: 'lighthouse', a: 2, b: 9, title: 'A costume in March',
    lines: [['a', 'Count October, it is March. Why are you dressed as a lighthouse?'], ['b', "Why AREN'T you?"], ['a', "It's the St. Patrick's parade. You are blocking the bagpipes."], ['b', 'I am illuminating the bagpipes.']],
    wise: 'Make it a green lighthouse. Everybody wins.' },
  { id: 'cookout', a: 5, b: 6, title: 'The best cookout',
    lines: [['a', 'Backyard Boulevard is cookout headquarters. It says so on the sign.'], ['b', 'Our cookout has fireworks.'], ['a', "Our cookout has Uncle June's ribs."], ['b', '...Okay. The ribs are very good.']],
    wise: 'Bring the ribs to the boardwalk and the fireworks to the backyard.' },
  { id: 'summer', a: 8, b: 7, title: 'Is summer over?',
    lines: [['a', 'Summer is over. Pencils are sharpened. Shoes are tied.'], ['b', 'Dear, it is still ninety-five degrees.'], ['a', 'Calendars do not care about degrees.'], ['b', 'Then the calendar may sit in the shade with me and have a lemonade.']],
    wise: 'Summer ends when the last popsicle is gone. Until then, you are both right.' },
  { id: 'fresh', a: 0, b: 8, title: 'The real fresh start',
    lines: [['a', 'New Year. Resolutions. A clean slate.'], ['b', 'Back to school. New notebooks. A REAL fresh start.'], ['a', 'Our fresh start has a parade.'], ['b', 'Ours has a seating chart.']],
    wise: 'You can start fresh on any day. Even a Tuesday.' },
  { id: 'feast', a: 4, b: 10, title: 'Who feeds everyone best?',
    lines: [['a', "Mother's Day brunch. Waffles. Strawberries. Flowers on the table."], ['b', 'Thanksgiving. Turkey. Dressing. Seven pies.'], ['a', "Seven? That's showing off."], ['b', 'It is eight. I hid one.']],
    wise: 'A full plate is a full plate. Can I have both?' },
  { id: 'magic', a: 9, b: 11, title: 'Which holiday is more magical?',
    lines: [['a', 'Halloween: the one night everyone gets to be someone else.'], ['b', 'Christmas: the one season everyone tries to be their best self.'], ['a', 'Your elves are just costumes with better manners.'], ['b', 'Your ghosts are just sheets that never got folded.']],
    wise: 'One night of make-believe and one season of giving. Merrywheel needs both.' },
  { id: 'daylight', a: 5, b: 1, title: 'Longest versus shortest',
    lines: [['a', 'We have the longest day of the year. The summer solstice. Pure daylight.'], ['b', 'We have the shortest month, and nobody complains about us.'], ['a', 'Everybody complains about February.'], ['b', '...Name one person.']],
    wise: 'Long or short, every day here has something worth celebrating.' },
  { id: 'weather', a: 2, b: 3, title: "Who's more unpredictable?",
    lines: [['a', 'In like a lion, out like a lamb. We are the original wild weather.'], ['b', 'Ha. We had sunshine, hail, and a rainbow before breakfast.'], ['a', "That's just showing off."], ['b', 'Also, I swapped all your umbrellas for tulips.']],
    wise: 'Wild weather means nobody in Merrywheel is ever bored.' },
  { id: 'loudest', a: 6, b: 9, title: "Who's the loudest?",
    lines: [['a', 'FIREWORKS. LOUDEST NIGHT OF THE YEAR.'], ['b', 'Haunted Hollow. Thunder. Organ music. Screaming.'], ['a', 'CAN YOU SAY THAT LOUDER?'], ['b', 'I can say it SPOOKIER.']],
    wise: 'You are both very loud. The Sundays would like you to know they are trying to nap.' },
  { id: 'order', a: 8, b: 9, title: 'Order versus chaos',
    lines: [['a', 'Count October, your costume parade has no schedule.'], ['b', 'Schedules are a costume for people who are afraid of fun.'], ['a', 'I have color-coded the haunted house.'], ['b', '...That is actually terrifying. I love it.']],
    wise: 'A well-organized haunted house is the scariest kind.' },
  { id: 'leap', a: 1, b: 2, title: 'The Leap Day guest room',
    lines: [['a', 'Twenty-Nine is our bonus child, and he deserves a parade.'], ['b', 'Every four years he shows up and sleeps in OUR guest room.'], ['a', 'He is royalty.'], ['b', 'He ate all our shamrock cookies.']],
    wise: 'Leap Day is a gift to everybody: one extra day to celebrate.' },
];
const SULK_LINES = ['Hmph. I heard you took the {r} side. I am not upset. I am just... over here.', 'Oh, it\'s you. The {r} fan. Hello, I suppose.', 'The {r}? Really? After everything we\'ve taught you?', 'I am fine. Totally fine. Ask the {r} how fine I am.'];
const SMUG_LINES = ['You agreed with us. Everyone saw. Everyone.', 'We were right, and you were wise enough to say so. Lovely.', 'Thank you for settling that. Correctly.'];

/* Time's children squabble too.  a/b: { k: sprite kind, n: name }  ·  rush: Seconds forget before you can answer */
const KID_ARGS = [
  { id: 'bestday', a: { k: 'day', n: 'Monday' }, b: { k: 'day', n: 'Friday' }, title: 'Who is the best day?',
    lines: [['b', 'Everybody loves me. I am the life of the party.'], ['a', 'Everybody loves you because you are not me.'], ['b', 'Want to come to my party?'], ['a', 'No. ...What time?']],
    wise: "Without Monday, Friday wouldn't feel half as good." },
  { id: 'weekend', a: { k: 'day', n: 'Saturday' }, b: { k: 'day', n: 'Sunday' }, title: 'Who is the real weekend?',
    lines: [['a', 'Cartoons. Pancakes. No alarms. I AM the weekend.'], ['b', '*yawn* I am also the weekend. Quietly.'], ['a', 'You sleep through half of it.'], ['b', 'That is the best half.']],
    wise: 'You are a team. Saturday plays, and Sunday rests up for it.' },
  { id: 'middle', a: { k: 'day', n: 'Wednesday' }, b: { k: 'day', n: 'Thursday' }, title: 'Who is stuck in the middle?',
    lines: [['a', 'I am the exact middle of the week. Everyone climbs over me.'], ['b', 'I am almost Friday. Almost. That is basically Friday.'], ['a', 'It is not basically Friday.'], ['b', 'Do not ruin this for me, Wednesday.']],
    wise: 'The middle holds everything together. And almost-Friday holds the hope.' },
  { id: 'tuesday', a: { k: 'day', n: 'Tuesday' }, b: { k: 'day', n: 'Monday' }, title: 'Nobody remembers Tuesday',
    lines: [['a', 'Nobody writes songs about Tuesday.'], ['b', 'At least nobody complains about you. Everybody complains about ME.'], ['a', 'I would LOVE to be complained about. That means they noticed.'], ['b', '...You can have some of my complaints.']],
    wise: 'Tuesday is the day things actually get done. Quiet heroes count.' },
  { id: 'sixty', a: { k: 'min', n: 'A Minute' }, b: { k: 'hour', n: 'An Hour' }, title: 'Who matters more?',
    lines: [['a', 'There are sixty of us inside every one of you. You are basically just us.'], ['b', 'And I keep all sixty of you in line. Every single hour.'], ['a', 'We could leave anytime.'], ['b', 'You literally cannot. That is how time works.']],
    wise: 'An Hour is just sixty Minutes holding hands.' },
  { id: 'hands', a: { k: 'sec', n: 'A Second' }, b: { k: 'min', n: 'A Minute' }, title: 'Who gets to ride the clock hand?',
    lines: [['a', 'Fastest hand! Round and round! Sixty laps!'], ['b', 'The minute hand actually points at something useful.'], ['a', 'Wheeeeee—'], ['x', 'The Second has already run three laps around the clock tower.']],
    wise: 'The clock needs every hand. Fast ones and slow ones.' },
  { id: 'faster', rush: true, a: { k: 'sec', n: 'A Second' }, b: { k: 'sec', n: 'Another Second' }, title: 'Two Seconds disagree',
    lines: [['a', 'Mine!'], ['b', 'MINE!'], ['a', 'Wait, what were we—'], ['x', 'By the time you open your mouth, both Seconds have forgotten and run off giggling. That is Seconds for you.']] },
  { id: 'schedule', a: { k: 'week', n: 'A Week' }, b: { k: 'day', n: 'Friday' }, title: 'Nobody asked for a schedule',
    lines: [['a', 'Friday, according to the schedule, your party ends at nine.'], ['b', 'Who made the schedule?'], ['a', 'I did. Nobody asked me to. I did it anyway.'], ['b', 'Can the schedule say midnight?']],
    wise: 'The Days make the fun, and the Weeks make sure the fun actually happens.' },
  { id: 'lastweek', a: { k: 'week', n: 'Week 52' }, b: { k: 'week', n: 'Week 1' }, title: 'Which week gets New Year?',
    lines: [['a', 'I am the last week of the year. I am basically the finale.'], ['b', 'I am the first week. I am basically the premiere.'], ['a', 'Finales are more dramatic.'], ['b', 'Premieres have better snacks.']],
    wise: 'Every ending is also a beginning. Share the snacks.' },
  { id: 'bedtime', a: { k: 'hour', n: 'The Bedtime Hour' }, b: { k: 'hour', n: 'The Breakfast Hour' }, title: 'Bedtime or breakfast?',
    lines: [['a', 'I tuck everyone in. Stories. Blankets. Lights out.'], ['b', 'I wake everyone up. Pancakes. Sunshine. Fresh starts.'], ['a', 'Nobody is happy to see you at six a.m.'], ['b', 'Nobody is happy to see you when they want one more story.']],
    wise: 'Good nights make good mornings. You need each other.' },
  { id: 'leapsec', a: { k: 'sec', n: 'The Leap Second' }, b: { k: 'min', n: 'A Minute' }, title: 'The Leap Second wants in',
    lines: [['a', 'Every few years I get added to the clock, just like Twenty-Nine gets added to February.'], ['b', 'You make my minute sixty-ONE seconds long. It is very confusing.'], ['a', 'I am special.'], ['b', 'You are extra. That is different.']],
    wise: "There's always room for one more. Even a tiny one." },
  { id: 'nap', a: { k: 'day', n: 'Friday' }, b: { k: 'day', n: 'Sunday' }, title: "Party at Sunday's house?",
    lines: [['a', 'Sunday, your porch is perfect for a party.'], ['b', 'My porch is for napping.'], ['a', 'A napping party.'], ['b', '...Go on.']],
    wise: 'Throw the party Friday and nap on Sunday. Everybody gets their turn.' },
];

/* Friendships: hearts, moments, keepsakes */
const HEART_AT = [0, 3, 7, 12, 18, 25];
const KEEPSAKES = [
  [['A Fresh Calendar', 'Every page blank, and full of possibilities.'], ["Grandpa January's Marching Baton", 'Still warm from the parade.']],
  [['A Box of Candy Hearts', 'Every single one says your name.'], ["Twenty-Nine's Tiny Crown", "On loan. He'll want it back in four years."]],
  [['A Pressed Four-Leaf Clover', 'Found by Captain March. One of his famous nine.'], ["Captain March's Weather Vane", 'It points where the wind is going to be.']],
  [['An Umbrella That Opens By Itself', 'Usually at the wrong time.'], ['A Jar of Rainbow', 'Cousin April swears it is real. It glows a little.']],
  [['A Pressed Corsage', 'From the first bloom on Blossom Boulevard.'], ["Mama May's Recipe Box", 'Every card says "made with love" at the bottom.']],
  [['An Engraved Grill Spatula', '"Cookout Crew" on the handle.'], ['The Spare Lawn Chair', 'There is always room at the cookout. This one is yours.']],
  [['A Box of Sparklers', 'For emergencies. Big Jim July defines "emergency" loosely.'], ["Big Jim July's Earmuffs", 'He has never once worn them.']],
  [['A Jubilee Ribbon', 'Gold, with twelve tiny stitches, one for each family.'], ['A Grand Pavilion Seat Cushion', 'Front row, forever.']],
  [['A Freshly Sharpened Pencil', 'Perfectly sharp. Professor September checked twice.'], ["Professor September's Pocket Planner", 'Already filled in and color-coded.']],
  [['A Spare Cape', 'Swishes very dramatically.'], ["Count October's Costume Trunk Key", 'The trunk is bigger on the inside.']],
  [['A Slice of Pie in Wax Paper', 'Granny November says it is "for the road."'], ["Granny November's Gravy Boat", 'Passed down for generations. Now to you.']],
  [['A Hand-Knit Sweater', 'One size fits everybody.'], ["Papa December's Jingle Bell", 'It rings whenever someone does something kind.']],
];
const MOMENTS = [
  ["Grandpa January shows you his very first resolution list, written on a yellowed card. Number one says: \"Be kinder.\" He taps it. \"Still working on that one. Every year.\"",
   "Before dawn, Grandpa January knocks on your door and walks you to First Light Avenue to watch the first sunrise of the year. \"Every year starts with one person who gets up early,\" he says. \"Thank you for being one.\""],
  ["Little Miss February admits she worries that being the shortest means being forgotten. You remind her that she has Valentine's Day. She goes pink and hands you the first candy heart of the year.",
   "Twenty-Nine summons you to his tiny throne and taps each of your shoulders with a breadstick. \"I name you Royal Friend of the Leap Year,\" he declares. The Februarys applaud. Little Miss February rolls her eyes, but she is smiling."],
  ["Captain March takes you up the windy hill and teaches you to read the wind. \"It always tells you what's coming,\" he says, \"if you're quiet enough to listen.\"",
   "On Harvest Heroes Lane, Captain March shows you his grandfather's worn-out hoe. \"Luck is nice,\" he says. \"Hands are better. Somebody's hands grew every bite you ever ate.\""],
  ["Cousin April confesses something: she makes it rain because she misses everyone when they stay inside. \"Rain makes strangers share the same awning,\" she says. \"Then they're not strangers.\"",
   "Cousin April gives you one perfect sunny day. On purpose. No tricks, no surprise hail. \"Don't get used to it,\" she says, but she lets it last until sunset."],
  ["Mama May asks about your mother. You tell her about Big Mama Mary. She writes the name, very carefully, in the Blossom Boulevard Book of Mothers, right on the first page.",
   "At dawn on Honor Avenue, Mama May places a single flower for her uncle who served, then hands one to you. \"First we remember,\" she says. \"Then we celebrate. That's the May way.\""],
  ["Uncle June pulls you behind the grill and whispers the secret rub for his famous ribs. \"Tell nobody,\" he says. \"Except family. Which you basically are now.\"",
   "On Freedom Street, Uncle June tells you his family has gathered for Juneteenth every single year, as far back as anyone can remember. \"We celebrate out loud,\" he says, \"because freedom should be loud.\" Then he hands you the first plate."],
  ["For the first time ever, Big Jim July whispers. \"I get nervous before every show.\" Then, at full volume: \"BUT IT'S FINE.\"",
   "Big Jim July lets you light the very first firework of the Fourth. It is a small one. It goes pop. He cries anyway. \"BEAUTIFUL,\" he sobs. \"PERFECT.\""],
  ["Lady August pours you a lemonade and explains why the families argue so much. \"Because each of them loves something with their whole heart,\" she says. \"That's not such a bad reason.\"",
   "Lady August saves you a seat at the Jubilee family table, right between the Januarys and the Decembers. \"Someone has to keep the peace,\" she says. \"I think it's you, dear.\""],
  ["Professor September shows you one page of his planner that is completely blank. It is labeled \"Unscheduled.\" \"Even I need a little of this,\" he admits.",
   "On Remembrance Row, Professor September lights a candle with you and tells you about the volunteers at Merrywheel's little firehouse, and how they run toward trouble so everybody else can run away from it."],
  ["Count October takes off his mask for the first time in years. Underneath is... another mask. He laughs until he has to sit down.",
   "On Heritage Trail, Count October goes quiet. \"The costumes are for fun,\" he says. \"The stories of this land are what matter.\" You walk the Three Sisters garden together without saying much at all."],
  ["Granny November makes you a plate \"for later,\" and another plate \"for later than that,\" and one more \"in case of company.\"",
   "On Valor Street, Granny November shows you her late husband's medals and the letters he wrote home. \"Say thank you to your veterans while they're here to hear it,\" she says. \"Every chance you get.\""],
  ["Papa December hands you a little box labeled \"Open now. Don't wait for Christmas.\" Inside is a handwritten card: \"You make Merrywheel brighter.\"",
   "On Christmas Eve, Papa December lifts you up so you can place the star on top of the great tree on Twinkle Lane. The whole street cheers. \"Every light here is for somebody,\" he says. \"That one's for you.\""],
];
const GIFT_LOVE = ['Oh, you remembered. This is exactly my favorite.', 'For me? Oh, you know us so well.', 'This is going right on the mantel. Right in the middle.'];
const GIFT_LIKE = ['How thoughtful. Thank you, really.', 'Well, isn\'t that nice. Thank you.', 'That\'s lovely. You didn\'t have to.'];
const GIFT_DISLIKE = { 10: ['twinkle', 'It is NOT December yet. ...But thank you. I will put it in the closet until it is.'], 0: ['countdown', 'A noisemaker? I JUST got the quiet back. ...Thank you. I suppose.'], 8: ['haunted', 'This is... very disorganized. But the thought is organized. Thank you.'] };
